### ISSUE TITLE
Customize path?

### ISSUE THREAD

**Issue by JuanCaicedo** [prettier/prettier-emacs#17]
Hi there! Would it be possible to support customizing the path to `prettier`?

I ask because I tend to locally install dev dependencies instead of globally. I get this at my emacs prompt 
```
$ which prettier
# ./node_modules/.bin/prettier
```

However if I execute `prettier-js` I get 
```
helm-M-x: Searching for program: No such file or directory, prettier
```

If it would be possible to support this, I'm willing to help 😃

**Comment by rcoedo** [comment]
I believe you may be able to do this already via the `prettier-js-command` defcustom 😄

**Comment by JuanCaicedo** [comment]
Yes that worked well! I haven't been able to find a way to configure it globally, but for now I added a `.dir-locals.el` for the projects that use prettier
```elisp
((nil
  (prettier-js-command
   .
   "/Users/JuanCaicedo/code/some-project/node_modules/\.bin/prettier")))
```

**Comment by JuanCaicedo** [comment]
Although actually I get a command saying that it's not a safe variable. Maybe it should be marked as [safe in the defcustom](https://emacs.stackexchange.com/questions/21575/mark-a-local-variable-safe-for-any-value)?

**Comment by rymndhng** [comment]
Is it possible for this to lean on https://github.com/codesuki/add-node-modules-path -- it seems undesirable when working in teams b/c the path is hard-coded.

**Comment by rcoedo** [comment]
I didn't know about that one @rymndhng, seems like the way to solve this. I'm going to start using it too, thanks!

**Comment by rcoedo** [comment]
@JuanCaicedo I have 0 knowledge of that part of emacs, but I tried customizing the variable via `custom.el` and it doesn't say it's unsafe for me.

If you have experience with defining customs, a PR would be appreciated!

**Comment by rymndhng** [comment]
Actually it does work out of the box! I am able to get this working by adding both hooks in my init.el, i.e for typescript:

```
(eval-after-load 'typescript-mode
    '(progn
       (add-hook 'typescript-mode-hook #'add-node-modules-path)
       (add-hook 'typescript-mode-hook #'prettier-js-mode)))
```

**Comment by rcoedo** [comment]
@rymndhng I think it can be very useful. Also, I'm adding this to my config right now 😄

**Comment by tauil** [comment]
FYI: I had the same issue and fixed by updating my emacs `exec-path`.

```
(setenv "PATH" (concat (getenv "PATH") ":/usr/local/bin"))
    (setq exec-path (append exec-path '("/usr/local/bin")))
```
