### ISSUE TITLE
Error when running with GNU Emacs 22.1.1 on MacOS

### ISSUE THREAD

**Issue by sbender9** [prettier/prettier-emacs#2]
Wrote /var/folders/w9/znwhy_ws05q9zxk7ly904jfh0000gr/T/prettier18190VDa.js      
apply: Wrong type argument: stringp, (:file "/var/folders/w9/znwhy_ws05q9zxk7ly904jfh0000gr/T/prettier18190iNg.js")

**Comment by sbender9** [comment]
Yeah, I'm an idiot. I guess I should install prettier first ;)

**Comment by sbender9** [comment]
Hmm. Still getting the same issue.

**Comment by rcoedo** [comment]
I've been investigating this issue and I've found that the primitive used to invoke the `prettier` command, `call-process`, has changed its API in emacs 24.

I guess this is kind of obvious, but is upgrading emacs a possibility? I understand that emacs 22.1.1 is what ships by default with MacOS, but it is a 10 years old release, and don't think we should be focusing on such old versions.

**Comment by sbender9** [comment]
That works. Actually had a newer version installed already but was testing via command-line with the older version. Working find now. Thanks!
