### ISSUE TITLE
[Feature Request] add an option to prefer prettier-eslint

### ISSUE THREAD

**Issue by maple-leaf** [prettier/prettier-emacs#31]
Please add an option to prefer `prettier-eslint` when has `prettier-eslint` installed locally or globally, use it, else use `prettier` :-)

**Comment by maple-leaf** [comment]
Thanks :-)

**Comment by benjamin-rood** [comment]
@rcoedo Hi Roman, still a emacs newbie, what do I need to configure in my init file to set the `prettier-js-command` variable to use `prettier-eslint`?

**Comment by nickmccurdy** [comment]
```emacs
(setq prettier-js-command "prettier-eslint")
```

**Comment by peter-wd-1** [comment]
How can I solve this error?
`
 (before-save-hook): Error running hook "prettier-js" because: (file-missing Searching for program No such file or directory prettier-eslint)
`
