### ISSUE TITLE
Can anybody write a prettier-standard emacs package?

### ISSUE THREAD

**Issue by adispring** [prettier/prettier-emacs#40]
using prettier-standard ：https://github.com/sheerun/prettier-standard

**Comment by nickmccurdy** [comment]
Set `prettier-js-command` to `"prettier-standard"`.

**Comment by adispring** [comment]
Yes，I replace all `prettier-js` to `prettier-standard-js`, it works!. This is my forked repo：https://github.com/adispring/prettier-emacs/blob/master/prettier-standard-js.el

and the temporary package install method:
```
    (prettier-standard-js :location (recipe
                         :fetcher github
                         :repo "adispring/prettier-emacs")) ;; prettier-standard，from github
```

**Comment by nickmccurdy** [comment]
Honestly you don't need your own package, it's a one line change to use with this package and you won't have to worry about maintaining updates.

```emacs
(setq prettier-js-command "prettier-standard")
```

**Comment by adispring** [comment]
Yeah, that's works. Great!

**Comment by ezmiller** [comment]
Is there a good way to change the prettier-js-command on a per project basis? I tried to use the directory variables feature by placing the following in a `.dir-locals.el` file:

```lisp
((nil . ((prettier-js-command . "prettier-standard"))))
```

But I got a message saying that it was dangerous to set the prettier-js-command on a per-file basis.

**Comment by adispring** [comment]
I use spacemacs, and this is my configuration: https://github.com/adispring/spacemacsDotD/blob/master/layers/adispring/packages.el#L176
