### ISSUE TITLE
Disable formatting on save

### ISSUE THREAD

**Issue by chrisalcantara** [prettier/prettier-emacs#55]
I'd like to bind `prettier-js` to a shortcut instead of having the minor mode run the command on save. Is this possible?

**Comment by rcoedo** [comment]
It is, just don't enable the mode at all and bind the shortcut to the `prettier-js` function.

**Comment by chrisalcantara** [comment]
I've tried that but get the following error: 

`Wrong type argument: commandp, prettier-js`. 

This is what my keybinding looks like:

`(eval-after-load 'js2-mode
  '(define-key js2-mode-map (kbd "C-c C-c") 'prettier-js))`

**Comment by chrisalcantara** [comment]
Closing. I solved the issue by loading my own version of prettier-emacs and commenting out the autoload function.
